openeuropa/oe_theme

composer.json, oe_theme.theme, templates/paragraphs/paragraph--oe-links-block.html.twig, tests/Kernel/ParagraphsTest.php
The configuration in OE Paragraphs has been updated, so the namespacing for all fields and derivates will be prefixed by "oe" instead of "oe_paragraphs".
This PR update the theme to be inline with oe_paragraphs fields!
=> OPENEUROPA-315: Rename configuration in OE Theme to use namespace oe.

README.md
Enable debug and disable twig cache manually while waiting for drupal console bug to be fixed, so it can be easier to switch between dev and production mode by using this command:
```
$ drupal site:mode dev  # Disable all caches.
$ drupal site:mode prod # Enable all caches.
```
=> OPENEUROPA-528: Instruction to enable debug and disable twig cache manually

oe_theme.theme, tests/Kernel/BreadcrumbTest.php
Fix breadcrumbs after the upgrade of ECL to 0.6.1. 
Add kernel tests to prevent issues in the future.
- Added: Add Kernel tests for breadcrumbs
- Fixed: Fix breadcrumbs after ECL update
=> OPENEUROPA-556: Fix breadcrumbs after ECL update and add kernel tests.

tests/Kernel/LanguageSwitcherTest.php, tests/features/theme-showcase.feature
Due to the changes in oe_multilingual, the tests regarding language labels are failing.
=> Language labels are translated in their native language.

patches/@ecl/ec-component-list-item+1.0.1.patch, tests/Kernel/ParagraphsTest.php, tests/fixtures/rendering.yml
New patch for @ECL node package to prevent empty sections to be rendered in EC Component List Item.
=> OPENEUROPA-677: New patch for @ECL node package

composer.json, templates/html/html.html.twig, tests/features/authentication.feature
The theme misses the important body classes that are used to identify whether the user is logged in, visiting an admin page, the node type etc. Without these it will not be possible to write effective JS, and the functional tests are also failing.
Ref. `template_preprocess_html()`
Ref. `html.html.twig` in the Classy theme.
=> OPENEUROPA-722: Make sure the default body classes are output

composer.json
I'm getting an error when installing the composer dependencies:
```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to DrupalComposer\DrupalScaffold\PrestissimoFileFetcher::__construct() must implement interface Composer\IO\IOInterface, array given, called in /home/pieter/v/oe_theme/vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 117 and defined in /home/pieter/v/oe_theme/vendor/drupal-composer/drupal-scaffold/src/PrestissimoFileFetcher.php:25
```
This is due to https://github.com/drupal-composer/drupal-scaffold/issues/79 for which a fix is released in drupal-scaffold 2.5.2.
This is a require-dev dependency so this version restriction does not affect the dependency chains of the websites that uses of the theme.
=> Update drupal scaffold

composer.json
The latest version no longer requires additional configuration in the
composer.json file.
=> OPENEUROPA-9: Update Drupal Scaffold.

oe_theme.theme, templates/patterns/banners/banner_hero.ui_patterns.yml, templates/patterns/button/button.ui_patterns.yml, templates/patterns/file_image/file_image.ui_patterns.yml, templates/patterns/file_video/file_video.ui_patterns.yml, templates/patterns/list_item/list_item.ui_patterns.yml, templates/patterns/list_item_blocks/list_item_block_one_column.ui_patterns.yml, templates/patterns/list_item_blocks/list_item_block_three_columns.ui_patterns.yml, templates/patterns/list_item_blocks/list_item_block_two_columns.ui_patterns.yml, templates/patterns/social_icon/social_icon.ui_patterns.yml
Use Drupal core \Drupal\Core\Url objects wherever necessary in custom ui_patterns.
- Changed: Url fields on ui_patterns now use \Drupal\Core\Url objects
=> OPENEUROPA-1381: Use Url objects on ui_patterns.

composer.json
Move "Deprecation warnings in Twig" patch to openeuropa/drupal-core-require-dev
- Updated: the dependency "openeuropa/drupal-core-require-dev"
- Removed: Remove the patch "Deprecation warnings in Twig code cause test failures."
=> OPENEUROPA-1387: Move "Deprecation warnings in Twig" patch to openeuropa/drupal-core-require-dev

config/optional/block.block.oe_theme_content_language_switcher.yml, config/optional/block.block.oe_theme_language_switcher.yml
The configs need to be renamed to actually work. Shipped config needs to be within the namespace of the module.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1549: Renaming config to actually get imported.

composer.json, modules/oe_theme_content_news/oe_theme_content_news.module, modules/oe_theme_content_news/src/Plugin/PageHeaderMetadata/NewsContentType.php, tests/features/news.feature, tests/features/page-header.feature
The publication date changed form timestamp to datefield. Change configuration and tests to reflect this.
- Added:
- Changed: Change configuration and tests to reflect change in publication date field.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1724: Modify processing of date fields.

modules/oe_theme_content_news/src/Plugin/PageHeaderMetadata/NewsContentType.php, modules/oe_theme_content_page/src/Plugin/PageHeaderMetadata/PageContentType.php, tests/features/page-header.feature
Node summary displayed in the page header has no filters applied.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
=> OPENEUROPA-1797: Ensure that text format filters are applied to the summary

oe_theme.theme, tests/Kernel/LanguageSwitcherTest.php
Make sure that the language switcher uses the prefix instead of the langcode.
=> OPENEUROPA-1806: PT-PT language switcher bug fix

modules/oe_theme_helper/oe_theme_helper.module
Change weight for `featured_image` to appear after `content_moderation_control`.
- Changed: Weight for `featured_image` decreased from -100 to -19.
=> OPENEUROPA-1807: featured_image must be after content_moderation_control

modules/oe_theme_helper/oe_theme_helper.module
We added the wrong module hook name in the previous PR https://github.com/openeuropa/oe_theme/pull/217/files#diff-3ae0518786005d63057fd2a74049f338R16
=> OPENEUROPA-1807: Make sure that moderation block is always right below the tabs - part 2

composer.json, config/optional/core.entity_view_display.media.av_portal_photo.oe_theme_main_content.yml, modules/oe_theme_helper/oe_theme_helper.install
Add responsive image field formatter and use it on the AV photo media.
- Added:
- Changed: Updated the AV Photo media display
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1775: Add responsive image formatter.

oe_theme.theme, tests/Kernel/BlockTest.php
Add ecl classes to block titles.
- Added: Add ecl classes to block titles.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1892: Add ecl classes to block titles.

js/message.js, oe_theme.libraries.yml, templates/status/status-messages.html.twig
Status messages can't be closed, add required js libraries to fix it.
- Added: Message js library.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1978: Add message library.

.drone.yml, templates/patterns/blockquote/pattern-blockquote.html.twig, tests/Kernel/Paragraphs/ParagraphsTest.php, tests/Kernel/fixtures/rendering.yml
Upgrade blockquote to ECL2.
- Added: Tests.
- Changed: The pattern of blockquote.
=> OPENEUROPA-1975: Upgrade blockquote to ECL2.

.drone.yml, modules/oe_theme_helper/src/Plugin/PageHeaderMetadata/EntityCanonicalRoutePage.php, oe_theme.theme, templates/navigation/pager.html.twig, tests/Kernel/PagerTest.php
Update pagination to ECL 2.0
- Added:
- Changed: Update pagination to ECL 2.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1976: ECL2: Update pager to ECL 2.0.

modules/oe_theme_helper/oe_theme_helper.install
This PR fixes the update hook introduced here: https://github.com/openeuropa/oe_theme/commit/eb0fc669e4665329b06c0122ce09fc8455016957
The problem was the assumption on the existence of the entity view display when in fact it was optional.
=> OPENEUROPA-1775: Fixing upgrade path of entity view display.

oe_theme.theme, templates/patterns/social_media_links/pattern-social-media-links-horizontal.html.twig, templates/patterns/social_media_links/pattern-social-media-links-vertical.html.twig, tests/Kernel/fixtures/rendering.yml
Update social media links to ECL 2.0
- Added:
- Changed: Update social media links to ECL 2.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1991: Update social media to ECL2.0.

templates/form/form--oe-search-search-form.html.twig, tests/Kernel/SearchFormBlockTest.php
Fix the template of Search box in the header.
- Changed: Fix a typo on the template.
=> OPENEUROPA-1996: Search box too small

behat.yml.dist, modules/oe_theme_helper/src/Plugin/Block/PageHeaderBlock.php, templates/patterns/page_header/pattern-page-header.html.twig, tests/Kernel/fixtures/rendering.yml, tests/features/page-header.feature
Add Identity on the page header.
- Added:
- Changed: Add identity site on page header pattern.
- Deprecated:
- Removed:
- Fixed:
- Security:
=> OPENEUROPA-2012: ECL2: Add Identity on the page header.

templates/field/field--oe-related-links.html.twig, tests/Kernel/ContentRenderTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2082: Change 'Related links' field label to h2.

composer.json, grumphp.yml.dist, modules/oe_theme_helper/src/Plugin/PageHeaderMetadata/EntityCanonicalRoutePage.php
Skip avoidance of deprecated error after new version of code review.
- Changed: code-review and ecl-twig-loader versions.
- Deprecated: incode phpcs ignore comments.
=> OPENEUROPA-2054: Skip avoidance of deprecated error after new version of code review.

modules/oe_theme_content_publication/config/install/core.date_format.oe_theme_publication_date.yml, modules/oe_theme_content_publication/oe_theme_content_publication.post_update.php, modules/oe_theme_content_publication/src/Plugin/PageHeaderMetadata/PublicationContentType.php, tests/Kernel/ContentRenderTest.php, tests/features/page-header.feature
The Publication page header needs to show the publication date.
- Added: Publication date to Publication page header metadata.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2135: Add publication date to Publication page header metadata

composer.json, oe_theme.theme, templates/patterns/banners/banner_video.ui_patterns.yml, templates/patterns/banners/pattern-banner-video.html.twig, tests/Kernel/fixtures/rendering.yml
Update video banner to ECL 2
- Added:
- Changed: Update video banner to ECL 2
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-1983: Update video banner to ECL2.

composer.json
Fix behat/mink-selenium2-driver missing branch by aliasing.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:  Fix behat/mink-selenium2-driver missing branch by aliasing.
- Security:
```sh
```
=> OPENEUROPA-2259: Fix behat/mink-selenium2-driver missing branch by aliasing.

oe_theme.theme
If you have a subtheme none of the icons shows up, because it's referencing to the active theme, which is the subtheme, not the base theme. Current solution works only if the active theme is the base theme.
=> Fix wrong path reference if using subtheme

README.md, templates/compositions/ec-component-content-item/content-item.html.twig, templates/ui_patterns_library/patterns-overview-page.html.twig, templates/ui_patterns_library/patterns-variant-meta-information.html.twig
Use ECL background image attribute and document image styles.
- Added: Use ECL background image attribute and document image styles.
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2192: Use ECL background image attribute and document image styles.

templates/compositions/ec-component-icons-with-text/icons-with-text.html.twig, templates/patterns/icons_with_text/icons_with_text.ui_patterns.yml, templates/patterns/icons_with_text/pattern-icons-with-text.html.twig, tests/Kernel/fixtures/rendering.yml
We can offer this as a pattern and then use such a pattern as needed when theming content types.
We will implement this as a composition, i.e. we won't be asking ECL team to provide this as a component.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2430: Create an "Icons with text" pattern.
