openeuropa/oe_theme

- README.md
- behat.yml.dist
- composer.json
- modules/oe_theme_demo/oe_theme_demo.links.menu.yml
- oe_theme.info.yml
- runner.yml.dist
- tests/Behat/Traits/UtilityTrait.php
- tests/Kernel/AbstractKernelTestBase.php
- tests/Kernel/BreadcrumbTest.php
- tests/Kernel/MultilingualAbstractKernelTestBase.php
- tests/features/site-branding.feature
- tests/features/theme-showcase.feature
> OPENEUROPA-635: Reduce patches on OpenEuropa Theme

- src/ValueObject/FileValueObject.php
- tests/Kernel/FilePatternRenderingTest.php
- tests/Unit/ValueObject/FileValueObjectTest.php
Fixing a bug in the FileValueObject.
> OPENEUROPA-1474: Fix fromFileEntity method to provide file URL by URI.

- CHANGELOG.md
Update CHANGELOG.md for the release 0.8.0.
- Changed: CHANGELOG.md
> OPENEUROPA-1562: Update CHANGELOG.md for the release 0.8.0.

- src/ValueObject/GalleryValueObject.php
- src/ValueObject/ImageMediaValueObject.php
- src/ValueObject/MediaValueObject.php
- tests/Unit/ValueObject/GalleryValueObjectTest.php
- tests/Unit/ValueObject/ImageMediaValueObjectTest.php
- tests/Unit/ValueObject/MediaValueObjectTest.php
Create MediaValueObject, GalleryValueObject and ImageMediaValueObject.
- Added: new objects MediaValueObject, GalleryValueObject and ImageMediaValueObject.
> OPENEUROPA-1531: Create MediaValueObject, GalleryValueObject and ImageMediaValueObject.

- CHANGELOG.md
Update the changelog for the release 0.9.0.
- Changed: Update changelog.md
> OPENEUROPA-1562: Update the changelog for the release 0.9.0.

- behat.yml.dist
- composer.json
- config/optional/block.block.oe_theme_search_form.yml
- oe_theme.info.yml
- oe_theme.theme
- runner.yml.dist
- templates/blocks/block--oe-search.html.twig
- templates/form/form--search-form.html.twig
- templates/form/input--search.html.twig
- tests/Behat/MinkContext.php
- tests/features/search-form.feature
Provide a simple search box that will submit searched terms to the external Europa search service
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1603: Provide a simple search box that will submit searched terms to the external Europa search service.

- CHANGELOG.md
Update changelog for new future release 0.10.0
- Changed: Changelog.
> OPENEUROPA-1635: Update the changelog for the release 0.10.0.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1696: Update CHANGELOG.md for 0.11.0 release.

- sass/style.scss
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1756: Fix styling of Apply button for moderation block.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Update CHANGELOG.md for 0.12.0 release.

- config/install/image.style.oe_theme_list_item_featured.yml
- config/install/image.style.oe_theme_list_item_featured_2x.yml
- oe_theme.info.yml
> OPENEUROPA-1752: List item featured image styles.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1745: Update CHANGELOG.md for 0.13.0 release.

- CHANGELOG.md
Create new release to use on ewcms
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1724: Prepare 0.13.1 release.

- config/optional/block.block.oe_theme_page_header.yml
- modules/oe_theme_content_news/src/Plugin/PageHeaderMetadata/NewsContentType.php
- modules/oe_theme_content_page/src/Plugin/PageHeaderMetadata/PageContentType.php
- modules/oe_theme_helper/oe_theme_helper.install
- modules/oe_theme_helper/src/Plugin/Block/PageHeaderBlock.php
- tests/features/page-header.feature
- tests/features/site-branding.feature
Show the page header on the homepage.
> OPENEUROPA-1812: Display the page header on the homepage.

- composer.json
- oe_theme.theme
- templates/paragraphs/paragraph--oe-contextual-navigation.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1832: Theming for Contextual navigation paragraph type.

- modules/oe_theme_helper/oe_theme_helper.install
> OPENEUROPA-1812: Fixing update hook type hinting.

- templates/status/status-messages.html.twig
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1809: Add margin-bottom for status messages.

- CHANGELOG.md
Create release 0.15.1.
- Added:
- Changed: CHANGELOG.md
- Deprecated:
- Removed:
- Fixed:
- Security:
> OPENEUROPA-1813: Create release 0.15.1.

- composer.json
> OPENEUROPA-1813: Upgrade to 8.7.

- CHANGELOG.md
Create release 0.16.0.
- Added:
- Changed: Changelog.md.
- Deprecated:
- Removed:
- Fixed:
- Security:
> OPENEUROPA-1813: Create release 0.16.0.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1890: Update CHANGELOG.md for release 0.17.0.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1864: Update changelog file for 1.0.0 release.

- .drone.yml
- js/accordions.js
- oe_theme.theme
- templates/patterns/accordion/pattern-accordion.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/fixtures/rendering.yml
Upgrade Accordion to ECL2.
- Added: JS for the accordion.
- Changed: Preprocess of the pattern accordion and kernel test.
> OPENEUROPA-1980: Upgrade Accordion to ECL2.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Update CHANGELOG.md for release 1.2.0.

- .drone.yml
- js/file_translations.js
- templates/patterns/file/pattern-file.html.twig
- templates/patterns/file_image/pattern-file-image.html.twig
- templates/patterns/file_translation/pattern-file-translation.html.twig
- templates/patterns/file_video/file_video.ui_patterns.yml
- templates/patterns/file_video/pattern-file-video.html.twig
- tests/Kernel/fixtures/patterns/file_pattern_rendering.yml
- tests/Kernel/fixtures/rendering.yml
Update the component pattern file.
- Added:
- Changed: Pattern file with and without translation.
> OPENEUROPA-1981: ECL2: Update the component pattern file to ECL2.

- package.json
Update @ecl to 2.7.0.
- Changed: Update @ecl packages.
> OPENEUROPA-1766: ECL2: Update @ecl to 2.7.0.

- templates/patterns/banners/banner_hero.ui_patterns.yml
- templates/patterns/banners/pattern-banner-hero.html.twig
- tests/Kernel/fixtures/rendering.yml
Update hero banner to ECL2.0
- Added:
- Changed:Update hero banner to ECL2.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1982: ECL2: Update hero banner to ECL2.0

- js/accordions.js
- js/file_translations.js
- js/message.js
- oe_theme.theme
- templates/patterns/file_translation/pattern-file-translation.html.twig
- tests/Kernel/fixtures/rendering.yml
Add link URL on file translation item and fix js issue.
- Fixed: File translation JS issue. 
- Changed: Link URL on file translation item
> OPENEUROPA-2026: ECL2: Add link on file translation item and fix js issue.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Update CHANGELOG.md for release 1.3.0.

- README.md
- ecl-builder.config.js
- js/accordions.js
- oe_theme.theme
- templates/patterns/accordion/accordion.ui_patterns.yml
- templates/patterns/accordion/pattern-accordion.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/fixtures/rendering.yml
Change Accordion to Accordion2 component.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
>  OPENEUROPA-2034: ECL2: Change Accordion to Accordion2 component.

- composer.json
- modules/oe_theme_content_policy/oe_theme_content_policy.module
- templates/field/timeline.html.twig
- tests/Kernel/TimelineTest.php
First, this https://github.com/openeuropa/oe_content/pull/88 has to be merged.
> OPENEUROPA-2061: Style timeline formatter with ECL and provide test.

- ecl-builder.config.js
- js/timelines.js
- oe_theme.libraries.yml
- oe_theme.theme
- templates/patterns/timeline/pattern-timeline.html.twig
- templates/patterns/timeline/timeline.ui_patterns.yml
- tests/Kernel/fixtures/rendering.yml
Port the timeline pattern component to ECL2.
> OPENEUROPA-2086: ECL 2.0: Timeline.

- ecl-builder.config.js
- js/inpage_navigation.js
- templates/paragraphs/paragraph--oe-content-row--variant-inpage_navigation.html.twig
- tests/Kernel/Paragraphs/ContentRowTest.php
https://ec.europa.eu/component-library/ec/components/navigation/inpage-navigation/usage/
> OPENEUROPA-2088: ECL 2.0: Inpage Navigation.

- package.json
Update @ecl packages to 2.10.0.
> OPENEUROPA-1766: Update @ecl packages to 2.10.0.

- CHANGELOG.md
- patches/@ecl/generic-component-timeline+1.8.0.patch
> OPENEUROPA-1766: Prepare release 1.6.0.

- js/context_nav.js
- templates/patterns/context_nav/pattern-context-nav.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/fixtures/rendering.yml
Add the contextual navigation component.
- Changed: Update contextual navigation to ECL2.
> OPENEUROPA-1984: ECL2: Add the contextual navigation component.

- templates/patterns/button/pattern-button.html.twig
- templates/patterns/social_icon/pattern-social-icon.html.twig
- tests/Kernel/fixtures/rendering.yml
Update the template pattern-social-icon.
> OPENEUROPA-2058: ECL 2.0: Social media Icons

- oe_theme.theme
- templates/compositions/ec-component-link-block/link-block.html.twig
- templates/patterns/link_block/pattern-link-block.html.twig
- templates/ui_patterns_library/patterns-overview-page.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/fixtures/rendering.yml
Add link-block template and its tests.
> OPENEUROPA-2092: ECL 2.0: Link blocks

- oe_theme.theme
- templates/compositions/ec-component-checkbox/checkbox.html.twig
- templates/form/form.html.twig
- templates/form/input--checkbox.html.twig
- templates/form/input--radio.html.twig
- templates/form/input--search.html.twig
- templates/form/input--submit.html.twig
- tests/Kernel/fixtures/rendering.yml
Add remaining form elements - Checkbox
> OPENEUROPA-2018: Add remaining form elements - Checkbox

- composer.json
Update docker-compose dependency of openeuropa/oe_corporate_blocks.
> OPENEUROPA-2159: Create OpenEuropa Corporate Blocks 2.x

- composer.json
Fix behat/mink-selenium2-driver missing branch by aliasing.
> OPENEUROPA-2259: Fix behat/mink-selenium2-driver missing branch by aliasing.

- modules/oe_theme_helper/src/TwigExtension/Filters.php
- oe_theme.theme
- src/ValueObject/DateValueObject.php
- src/ValueObject/DateValueObjectInterface.php
- templates/compositions/ec-component-content-item/content-item-date.html.twig
- templates/compositions/ec-component-date-block/date-block.html.twig
- templates/patterns/date_block/pattern-date-block.html.twig
- templates/patterns/list_item/pattern-list-item--variant-date.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/Patterns/DateBlockPatternRenderingTest.php
- tests/Kernel/ValueObject/DateTimeTestBase.php
- tests/Kernel/fixtures/patterns/date_block_pattern_rendering.yml
- tests/Kernel/fixtures/rendering.yml
- tests/Unit/ValueObject/DateValueObjectTest.php
- tests/Unit/fixtures/value_object/date_value_object.yml
> OPENEUROPA-1985: Update date blocks pattern.

- modules/oe_theme_helper/src/TwigExtension/Filters.php
- oe_theme.theme
- templates/form/form--oe-search-search-form.html.twig
> OPENEUROPA-2083: ECL 2.0: Use extra_blocks on form.

- templates/patterns/list_item/pattern-list-item--variant-block.html.twig
- tests/Kernel/Paragraphs/ParagraphsTest.php
- tests/Kernel/fixtures/rendering.yml
Add list item variant block and tests.
> OPENEUROPA-2124: ECL 2.0: List item patterns (other)

- CHANGELOG.md
Update the changelog for the release 2.0.0-alpha1.
> OPENEUROPA-1766: Update the changelog for the release 2.0.0-alpha1.

- templates/form/input--radio.html.twig
Radios are missing the default state.
> Pass the checked state to radio buttons.

- oe_theme.theme
- templates/pattern-previews/pattern-featured-item--preview.html.twig
- templates/patterns/featured_item/featured_item.ui_patterns.yml
- templates/patterns/featured_item/pattern-featured-item.html.twig
- templates/ui_patterns_library/patterns-single-page.html.twig
- tests/Kernel/fixtures/rendering.yml
Update featured item.
- Added: 
- Changed: Updated featured item using the card template.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-1988: Update featured item using card.

- templates/patterns/tag/pattern-tag.html.twig
- templates/patterns/tag/tag.ui_patterns.yml
- tests/Kernel/fixtures/rendering.yml
Simple implementation for the tag component
- Added: Tag pattern
> Add "Tag" pattern

- composer.json
- oe_theme.theme
- templates/paragraphs/paragraph--oe-social-media-follow.html.twig
- tests/Kernel/Paragraphs/ParagraphsTestBase.php
- tests/Kernel/Paragraphs/SocialMediaFollowTest.php
Style Social media follow paragraph for 2.x
- Added: template, preprocess and tests for Social media follow
> OPENEUROPA-2471: Style Social media follow paragraph for 2.x

- .drone.yml
- ecl-builder.config.js
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-2467: Remove SASS source mapping from final CSS artifacts.
